const projects = [
    {
        id: 1,
        title: 'Tickety web',
        img: require('../../assets/img/mockup 1.webp'),
        description: 'Developed a full-stack web application for event ticketing, complete with administrative functionality and transaction management, using Laravel.',
        link: 'https://github.com/LaluIman/E-commerce-Laravel',
        type: ["Website", "Laravel"],
    },
    {
        id: 2,
        title: 'UniStore',
        img: require('../../assets/img/mockup 2.webp'),
        description: 'Designed and implemented a UI-focused e-commerce mobile application using Flutter, delivering an optimized user interface and seamless user experience.',
        link: 'https://github.com/LaluIman/UniStore_UI',
        type: ["Mobile", "Flutter"],
    },
    {
        id: 3,
        title: 'Al-Maratush Shalihah',
        img: require('../../assets/img/mockup 3.webp'),
        description: 'Built an engaging school website with a fun, interactive theme and user-friendly interface, offering a modern and appealing digital presence.',
        link: '',
        type: ["Website", "CSS", "JS"],
    },
    {
        id: 4,
        title: 'CookBook',
        img: require('../../assets/img/mockup 4.webp'),
        description: 'Developed a mobile cooking recipe app with a clean, intuitive design and efficient layout to enhance user experience and navigation.',
        link: 'https://github.com/LaluIman/CookBookApp',
        type: ["Mobile", "React Native"],
    },
    {
        id: 5,
        title: 'Voyager',
        img: require('../../assets/img/mockup 5.webp'),
        description: 'Created a travel application UI using Flutter, focusing on delivering a visually appealing interface and smooth user interactions.',
        link: 'https://github.com/LaluIman/Voyager_TravelApp',
        type: ["Mobile", "Flutter"],
    },
    {
        id: 6,
        title: 'Nada Nusantara',
        img: require('../../assets/img/mockup 6.webp'),
        description: 'Developed an interactive mobile app focused on showcasing traditional Indonesian musical instruments, leveraging Flutter to deliver a rich user experience.',
        link: 'https://github.com/LaluIman/Nada_Nusantara',
        type: ["Mobile", "Flutter"],
    },
    {
        id: 7,
        title: 'Movieflow',
        img: require('../../assets/img/mockup 7.webp'),
        description: 'Designed and built a mobile app using SwiftUI for seamless browsing and discovery of movies with a clean, modern interface.',
        link: 'https://github.com/LaluIman/MoviesApp',
        type: ["Mobile", "SwiftUI"],
    },
    {
        id: 8,
        title: 'Gopro website',
        img: require('../../assets/img/mockup 8.webp'),
        description: 'Developed a responsive website for showcasing GoPro products, using TailwindCSS to create a visually appealing and responsive layout.',
        link: 'https://goprowebsite.vercel.app/',
        type: ["Website", "TailwindCSS"],
    },
    {
        id: 9,
        title: 'Kutaire',
        img: require('../../assets/img/mockup 9.webp'),
        description: 'Developed a modern, responsive website utilizing TailwindCSS to deliver a dynamic user experience with a focus on clean design and usability.',
        link: 'https://laluiman.github.io/Kutaire/',
        type: ["Website", "TailwindCSS"],
    },
];

export default projects;
